environment:
  my_secret:
    secure: Q3rkG9Khjq7DVfHJMdDzTw==

install:
- ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
- cmd: appveyor-tools\secure-file -decrypt my-secret.txt.enc -secret %my_secret%
- sh: ./appveyor-tools/secure-file -decrypt my-secret.txt.enc -secret $my_secret

test_script:
- ps: $originalValue = (Get-Content my-secret.txt)
- ps: if($originalValue -ne 'Hello, world!') { throw "Decrypted string is not equal to the original one: $originalValue"; }

build: off